### ISSUE TITLE
Database creation

### ISSUE THREAD

**Issue by alemanyp** [sonata-nfv/tng-slice-mngr#10]
The database would be outside the container. Containers are mortal - we will lose these dictionaries.

**Comment by rvilalta** [comment]
NSI should be allocated in repo: https://github.com/sonata-nfv/tng-rep
NST should be allocated in catalog: https://github.com/sonata-nfv/son-catalogue-repos

**Comment by alemanyp** [comment]
NSI and NST allocated where they have to be allocated.
