### ISSUE TITLE
Fetch a Network Slice Template

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-slice-mngr#2]
Originated from [#212](https://git.cs.upb.de/5gtango/UserStories/issues/212).

**Comment by rvilalta** [comment]
POST CREATE NST curl -i -H "Content-Type:application/json" -X POST -d'{"id":1, "nstId":1, "nstName":"tango_NST", "nstVersion":2, "nstDesigner":"5gtango", "nstInvariantId":"1", "nstNsdIds":[{"nstNsdId":1},{"nstNsdId":2}], "nstOnboardingState":"ENABLED", "nstOperationalState":"ENABLED", "nstUsageState":"IN_USE", "notificationTypes":"Notification of tango_NST", "userDefinedData":"Data"}' http://127.0.0.1:5998/nst/v1/descriptors
