### ISSUE TITLE
Support default params for NST instantiation requests

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-slice-mngr#62]

**Comment by alemanyp** [comment]
@jbonnet what do you mean?? which default params? please, could you give some more details?

**Comment by jbonnet** [comment]
I mean, if the Portal/GK does not provide an `sla_id`, what should happen? Should the GK pass the Slicer an `sla_id` that is `''` (an empty string), or not send it at all? In better words: which parameters are mandatory and whicg are optional?

**Comment by alemanyp** [comment]
if the portal/GK doesn't provide a sla_id is already working. in that case, the protal sends "sla_id":"None" and the slice-mngr sends the requests without any sla associated.

All parameters are mandatory except the sla_id, this is defined alreay in the protal with the following symbol (*).

Ti create a slice template, all parameters are required (name, author, vendor, version, serv_uuid)
To create a slice instantiation, all params are required (name, author, vendor, version, serv_uuid) EXCEPT sla_id.

**Comment by jbonnet** [comment]
Wait, @alemanyp 
> ...To create a slice instantiation, all params are required (name, author, vendor, version, serv_uuid) EXCEPT sla_id.

I thought Slice Instantiation only needed the Slice Template ID... why repeating name, author, vendor, version and serv_uuid?

**Comment by alemanyp** [comment]
Sorry, my mistake. The slice instantiation simply needs the NetSlice Template_id and a description (which is not required).

Abou the description, lately, I'm thinking to move it from the instantiation to the template as it makes more sense to have a description of a template (to know which services or functions has).

**Comment by jbonnet** [comment]
> ...Abou the description, lately, I'm thinking to move it from the instantiation to the template as it makes more sense to have a description of a template (to know which services or functions has).

Probably, but we might have something to say about a slice instance as well, that goes beyond a name. `ALB's Slice for 5GTANGO work`, for instance...

**Comment by alemanyp** [comment]
> Probably, but we might have something to say about a slice instance as well, that goes beyond a name. `ALB's Slice for 5GTANGO work`, for instance, would help the user in finding the slice instance among the rest (I know there's also the `name`).

True! Then the best option is to put description in both forms; required for the template and optional for the instantiation. What do you think?

**Comment by jbonnet** [comment]
Perfect!

**Comment by alemanyp** [comment]
Added to the slice code, missing the related modifications in the portal design formulars to close this issue
